# Loan EMI Calculator(Task 1)
P = float(input("Enter Principal Amount: "))
annual_rate = float(input("Enter Annual Interest Rate (%): "))
N = int(input("Enter Loan Tenure (Months): "))
R = annual_rate / (12 * 100)
EMI = (P * R * (1 + R) ** N) / ((1 + R) ** N - 1)
print("\n----- EMI DETAILS -----")
print(f"Principal Amount : ₹{P:.2f}")
print(f"Interest Rate    : {annual_rate}%")
print(f"Loan Tenure      : {N} months")
print(f"Monthly EMI      : ₹{EMI:.2f}")